<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] ?? 'Location Comparison Report' }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; padding-bottom: 20px; }
        .header h1 { margin: 0; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $data['title'] ?? 'Location Comparison Report' }}</h1>
        <div>{{ $data['date_range']['from'] ?? '' }} to {{ $data['date_range']['to'] ?? '' }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Address</th>
                <th>Total Reviews</th>
                <th>Avg Rating</th>
                <th>Response Rate</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['locations'] ?? [] as $location)
            <tr>
                <td>{{ $location['name'] ?? 'N/A' }}</td>
                <td>{{ $location['address'] ?? 'N/A' }}</td>
                <td>{{ $location['total_reviews'] ?? 0 }}</td>
                <td>{{ $location['average_rating'] ?? 0 }}</td>
                <td>{{ $location['response_rate'] ?? 0 }}%</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align: center;">No locations found</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">{{ $data['branding']['footer_text'] ?? 'Generated by ' . config('app.name') }}</div>
</body>
</html>
