<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] ?? 'Reviews Report' }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; padding-bottom: 20px; }
        .header h1 { margin: 0; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        .header .date { color: #666; font-size: 11px; }
        .summary { background: #f5f5f5; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .summary-item { display: inline-block; margin-right: 30px; }
        .summary-label { font-weight: bold; color: #666; }
        .summary-value { font-size: 18px; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; vertical-align: top; }
        tr:nth-child(even) { background: #f9f9f9; }
        .rating { font-weight: bold; }
        .rating-5, .rating-4 { color: #27ae60; }
        .rating-3 { color: #f39c12; }
        .rating-2, .rating-1 { color: #e74c3c; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 15px; }
        .content { max-width: 300px; }
    </style>
</head>
<body>
    <div class="header">
        @if(!empty($data['branding']['logo_url']))
        <img src="{{ $data['branding']['logo_url'] }}" alt="Logo" style="max-height: 50px; margin-bottom: 10px;">
        @endif
        <h1>{{ $data['branding']['company_name'] ?? $data['title'] ?? 'Reviews Report' }}</h1>
        <div class="date">Generated: {{ $data['generated_at'] }} | Period: {{ $data['date_range']['from'] ?? 'N/A' }} to {{ $data['date_range']['to'] ?? 'N/A' }}</div>
    </div>

    <div class="summary">
        <div class="summary-item">
            <div class="summary-label">Total Reviews</div>
            <div class="summary-value">{{ $data['summary']['total_reviews'] ?? 0 }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Average Rating</div>
            <div class="summary-value">{{ $data['summary']['average_rating'] ?? 0 }} / 5</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Author</th>
                <th>Rating</th>
                <th>Review</th>
                <th>Platform</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['reviews'] ?? [] as $review)
            <tr>
                <td>{{ $review['author'] ?? 'Anonymous' }}</td>
                <td class="rating rating-{{ $review['rating'] ?? 0 }}">{{ $review['rating'] ?? 'N/A' }} ★</td>
                <td class="content">{{ \Illuminate\Support\Str::limit($review['content'] ?? '', 200) }}</td>
                <td>{{ ucfirst($review['platform'] ?? '') }}</td>
                <td>{{ $review['published_at'] ?? '' }}</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align: center;">No reviews found</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        {{ $data['branding']['footer_text'] ?? 'Generated by ' . config('app.name') }}
    </div>
</body>
</html>
