<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] ?? 'Sentiment Analysis Report' }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; padding-bottom: 20px; }
        .header h1 { margin: 0; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        .summary { background: #f5f5f5; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .sentiment-positive { color: #27ae60; }
        .sentiment-negative { color: #e74c3c; }
        .sentiment-neutral { color: #95a5a6; }
        .sentiment-mixed { color: #f39c12; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $data['title'] ?? 'Sentiment Analysis Report' }}</h1>
        <div>{{ $data['date_range']['from'] ?? '' }} to {{ $data['date_range']['to'] ?? '' }}</div>
    </div>

    <div class="summary">
        <p><strong>Total Analyzed:</strong> {{ $data['summary']['total_analyzed'] ?? 0 }}</p>
        <p><strong>Average Sentiment Score:</strong> {{ $data['summary']['average_sentiment_score'] ?? 0 }}</p>
        @if(!empty($data['summary']['sentiment_distribution']))
        <p><strong>Distribution:</strong>
            @foreach($data['summary']['sentiment_distribution'] as $sentiment => $count)
            <span class="sentiment-{{ $sentiment }}">{{ ucfirst($sentiment) }}: {{ $count }}</span> |
            @endforeach
        </p>
        @endif
    </div>

    <table>
        <thead>
            <tr><th>Author</th><th>Sentiment</th><th>Score</th><th>Content</th><th>Key Phrases</th></tr>
        </thead>
        <tbody>
            @forelse($data['reviews'] ?? [] as $review)
            <tr>
                <td>{{ $review['author'] ?? 'Anonymous' }}</td>
                <td class="sentiment-{{ $review['sentiment'] ?? 'neutral' }}">{{ ucfirst($review['sentiment'] ?? 'N/A') }}</td>
                <td>{{ $review['sentiment_score'] ?? 'N/A' }}</td>
                <td>{{ \Illuminate\Support\Str::limit($review['content'] ?? '', 150) }}</td>
                <td>{{ is_array($review['key_phrases'] ?? null) ? implode(', ', $review['key_phrases']) : '' }}</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align: center;">No sentiment data found</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">{{ $data['branding']['footer_text'] ?? 'Generated by ' . config('app.name') }}</div>
</body>
</html>
