<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] ?? 'Summary Report' }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; padding-bottom: 20px; }
        .header h1 { margin: 0; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        .metrics { display: flex; justify-content: space-around; margin: 30px 0; }
        .metric { text-align: center; padding: 20px; background: #f5f5f5; border-radius: 8px; width: 22%; }
        .metric-value { font-size: 28px; font-weight: bold; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        .metric-label { color: #666; margin-top: 5px; }
        .section { margin: 30px 0; }
        .section h2 { color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f5f5f5; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $data['title'] ?? 'Summary Report' }}</h1>
        <div>{{ $data['date_range']['from'] ?? '' }} to {{ $data['date_range']['to'] ?? '' }}</div>
    </div>

    <div class="metrics">
        <div class="metric">
            <div class="metric-value">{{ $data['overview']['total_reviews'] ?? 0 }}</div>
            <div class="metric-label">Total Reviews</div>
        </div>
        <div class="metric">
            <div class="metric-value">{{ $data['overview']['average_rating'] ?? 0 }}</div>
            <div class="metric-label">Avg Rating</div>
        </div>
        <div class="metric">
            <div class="metric-value">{{ $data['overview']['total_locations'] ?? 0 }}</div>
            <div class="metric-label">Locations</div>
        </div>
        <div class="metric">
            <div class="metric-value">{{ $data['overview']['response_rate'] ?? 0 }}%</div>
            <div class="metric-label">Response Rate</div>
        </div>
    </div>

    <div class="section">
        <h2>Rating Distribution</h2>
        <table>
            @foreach([5,4,3,2,1] as $rating)
            <tr>
                <td>{{ $rating }} Stars</td>
                <td>{{ $data['rating_distribution'][$rating] ?? 0 }} reviews</td>
            </tr>
            @endforeach
        </table>
    </div>

    <div class="section">
        <h2>By Platform</h2>
        <table>
            <tr><th>Platform</th><th>Reviews</th><th>Avg Rating</th></tr>
            @forelse($data['by_platform'] ?? [] as $platform => $stats)
            <tr>
                <td>{{ ucfirst($platform) }}</td>
                <td>{{ $stats['count'] ?? 0 }}</td>
                <td>{{ $stats['average_rating'] ?? 0 }}</td>
            </tr>
            @empty
            <tr><td colspan="3">No data</td></tr>
            @endforelse
        </table>
    </div>

    <div class="footer">{{ $data['branding']['footer_text'] ?? 'Generated by ' . config('app.name') }}</div>
</body>
</html>
