<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] ?? 'Trends Report' }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; padding-bottom: 20px; }
        .header h1 { margin: 0; color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        .summary { background: #f5f5f5; padding: 15px; margin-bottom: 20px; border-radius: 5px; text-align: center; }
        .section { margin: 30px 0; }
        .section h2 { color: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; }
        table { width: 100%; border-collapse: collapse; }
        th { background: {{ $data['branding']['primary_color'] ?? '#1a1a1a' }}; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $data['title'] ?? 'Trends Report' }}</h1>
        <div>{{ $data['date_range']['from'] ?? '' }} to {{ $data['date_range']['to'] ?? '' }}</div>
    </div>

    <div class="summary">
        <strong>Total Reviews:</strong> {{ $data['summary']['total_reviews'] ?? 0 }} |
        <strong>Average Rating:</strong> {{ $data['summary']['average_rating'] ?? 0 }}
    </div>

    <div class="section">
        <h2>Monthly Trends</h2>
        <table>
            <tr><th>Month</th><th>Reviews</th><th>Avg Rating</th></tr>
            @forelse($data['trends_by_month'] ?? [] as $month => $stats)
            <tr>
                <td>{{ $month }}</td>
                <td>{{ $stats['count'] ?? 0 }}</td>
                <td>{{ $stats['average_rating'] ?? 0 }}</td>
            </tr>
            @empty
            <tr><td colspan="3">No data</td></tr>
            @endforelse
        </table>
    </div>

    <div class="footer">{{ $data['branding']['footer_text'] ?? 'Generated by ' . config('app.name') }}</div>
</body>
</html>
